# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TEDxJoven@CNBA
email: TEDxJovenCNBA@gmail.com
description: Los charlas TED son formas de transmitir ideas que potencien al público a producir un cambio, a generar nuevas ideas, a despertar pasiones, a transformar lo que nos rodea, a plantearse nuevos paradigmas, a soñar, a poner en acción nuestra creatividad e imaginación, en fin, a creer en nosotros mismos.
baseurl: "/pagina" # the subpath of your site, e.g. /blog
url: "http://tedxcnba.github.io" # the base hostname & protocol for your site
twitter_username: TEDxJovenCNBA

# Build settings
markdown: kramdown